Update external docs from core repo

diff --git a/silogen-public-docs/.husky/pre-push b/silogen-public-docs/.husky/pre-push
--- a/silogen-public-docs/.husky/pre-push
+++ b/silogen-public-docs/.husky/pre-push
@@ -1,3 +1,7 @@
+#!/bin/sh
+# end this script as soon as any command fails
+set -e
+
 # Run only if there are changes in the docs/silogen-public-docs directory
 if git diff --name-only HEAD^ HEAD | grep --quiet "docs/silogen-public-docs"; then
 
@@ -11,10 +15,10 @@ if git diff --name-only HEAD^ HEAD | grep --quiet "docs/silogen-public-docs"; th
     echo "Running ESLint..."
     npm run lint
 
-    echo "Building docusaurus external docs"
-    npm run docusaurusbuild
-
     echo "Running tests"
     npm run test
+
+    echo "Building the project"
+    npm run build
 
 fi
